---
- name: Install nginx and git
  become: true
  apt:
    name: "{{ lighthouse_packages }}"
    update_cache: yes
    notify: start-nginx

- name: set config nginx
  become: true
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: reload-nginx