---
- name: Vector | Download packages
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    dest: "./vector-{{ vector_version }}-1.amd64.deb"
- name: Vector | Install packages
  become: true
    apt:
      deb: 
         ./vector-{{ vector_version }}-1.amd64.deb
- name: Vector | template config
  become: true
  ansible.builtin.template:
    src: "vector.yml.j2"
    dest: "{{ vector_config_dir }}/vector.yml"
    mode: "0644"

- name: Vector | service
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /lib/systemd/system/vector.service
    mode: "0644"
   notify: Start Vector service
