---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      become_method: sudo
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_amd64.deb"
            dest: "./{{ item }}_{{ clickhouse_version }}.amd64.deb"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
            dest: "./clickhouse-common-static_{{ clickhouse_version }}.amd64.deb"
    - name: Install clickhouse packages
      apt:
            clickhouse-common-static_{{ clickhouse_version }}.amd64.deb
            clickhouse-client_{{ clickhouse_version }}.amd64.deb
            clickhouse-server_{{ clickhouse_version }}.amd64.deb
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  handlers:
    - name: Start Vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: started
  tasks:
    - name: Vector | Download packages
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
        dest: "./vector-{{ vector_version }}-1.amd64.deb"
    - name: Vector | Install packages
      become: true
      apt:
        deb: 
              ./vector-{{ vector_version }}-1.amd64.deb
    - name: Vector | template config
      become: true
      ansible.builtin.template:
        src: "vector.yml.j2"
        dest: "{{ vector_config_dir }}/vector.yml"
        mode: "0644"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"

    - name: Vector | service
      become: true
      ansible.builtin.template:
        src: vector.service.j2
        dest: /lib/systemd/system/vector.service
        mode: "0644"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        backup: true
      notify: Start Vector service

- name: install nginx
  hosts: lighthouse
  handlers:
   - name: start-nginx
     become: true
     service: 
       name: nginx
       state: started  
   - name: reload-nginx
     become: true
     service: 
       name: nginx
       state: restarted
  tasks:
   - name: Install nginx and git
     become: true
     apt:
       name: "{{ lighthouse_packages }}"
       update_cache: yes
     notify: start-nginx

   - name: set config nginx
     become: true
     template:
       src: templates/nginx.conf.j2
       dest: /etc/nginx/nginx.conf
       mode: "0644"
     notify: reload-nginx
- name: install lighthouse
  hosts: lighthouse
  handlers: 
   - name: reload-nginx
     become: true
     service: 
       name: nginx
       state: restarted
  tasks:
   - name: lighthouse | Copy from git
     become: true
     git:
       repo: https://github.com/VKCOM/lighthouse.git
       version: master
       dest: "{{ lighthouse_data }}"

   - name: lighthouse | set config site
     become: true
     template:
       src: templates/default.conf.j2
       dest: /etc/nginx/conf.d/nginx.conf
       mode: "0644"
     notify: reload-nginx