vector_url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
vector_version: 0.35.0
vector_config_dir: "/etc/vector"
vector_config:
  sources:
    logs_file:
      type: file
      include:
       - /home/vector/logs/*.logs
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - logs_file
      database: sample
      endpoint: http://192.168.31.75:8123
      table: some_log
      auth:
        password: nolar
        user: nolar
      compression: gzip
      skip_unknown_fields: true