---
clickhouse:
  hosts:
    clickhouse:
      ansible_host: 158.160.63.232
lighthouse:
  hosts:
    lighthouse:
      ansible_host: 84.201.128.70
vector:
  hosts:
    vector:
      ansible_host: 51.250.74.83
